Controllers/Account/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace DengiAdvisor_CRM.Core.UI.Controllers
{

    class person
    {
        public string name { get; set; }
        public string mobile { get; set; }
    }
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult SignIn()
        {
            return View();
        }

        public string Index()
        {
            List<person> data = new List<person>();
           data.Add(new person { name="neeraj",mobile="7017064248"});
            var jsondata = new JavaScriptSerializer().Serialize(data);
            return jsondata;
        }
        public ActionResult SuperAdmin()
        {
            return View();
        }
    }
}

Controllers/Account/Bank/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.Bank
{
    public class BankController : Controller
    {
        // GET: Bank
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Bank()
        {
            return View();
        }
    }
}

Controllers/Account/Banker/BankerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.Banker
{
    public class BankerController : Controller
    {
        // GET: Banker
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Banker()
        {
            return View();
        }
    }
}

Controllers/Account/DSA/DSAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.DSA
{
    public class DSAController : Controller
    {
        // GET: DSA
        public ActionResult DSA()
        {
            return View();
        }
        public ActionResult DSAUser()
        {
            return View();
        }
        public ActionResult Rought()
        {
            return View();
        }
    }
}

Controllers/Account/Loan/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.Loan
{
    public class LoanController : Controller
    {
        // GET: Loan
        public ActionResult DailyPickup()
        {
            return View();
        }

        public ActionResult SendToBank()
        {
            return View();
        }

        public ActionResult LoggedIn()
        {
            return View();
        }

        public ActionResult CreditProcess()
        {
            return View();
        }
        public ActionResult ApprovedFile()
        {
            return View();
        }
        public ActionResult DisbursedFile()
        {
            return View();
        }
        public ActionResult RejectedFile()
        {
            return View();
        }
    }
}

Controllers/Account/Office/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.Office
{
    //[Authorize]
    public class OfficeController : Controller
    {
        // GET: Office
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Registration()
        {
            return View();
        }
        public ActionResult UserRegistration()
        {
            return View();
        }
        public ActionResult UserEmailVerification(string email)
        {
            string []data = email.Split(':');
            ViewBag.UserEmail = data[0];
            ViewBag.usertype = data[1];

            return View();
        }
        public ActionResult success(string email)
        {
            return View();
        }

        public string DecryptString(string encrString)
        {
            byte[] b;
            string decrypted;
            try
            {
                b = Convert.FromBase64String(encrString);
                decrypted = System.Text.ASCIIEncoding.ASCII.GetString(b);
            }
            catch (FormatException fe)
            {
                decrypted = "";
            }
            return decrypted;
        }

        public string EnryptString(string strEncrypted)
        {
            byte[] b = System.Text.ASCIIEncoding.ASCII.GetBytes(strEncrypted);
            string encrypted = Convert.ToBase64String(b);
            return encrypted;
        }

    }
}

Controllers/Account/SuperAdmin/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.SuperAdmin
{
    public class SuperAdminController : Controller
    {
        // GET: SuperAdmin
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

Controllers/Account/dsa-admin/dsa_adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Account.dsa_admin
{
    public class dsa_adminController : Controller
    {
        // GET: dsa_admin
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult account()
        {
            return View();
        }

        public ActionResult dailypickup()
        {
            return View();
        }
        public ActionResult banklogins()
        {
            return View();
        }
        public ActionResult pendencies()
        {
            return View();
        }
        public ActionResult creditprocess()
        {
            return View();
        }
        public ActionResult disbursedfiles()
        {
            return View();
        }
        public ActionResult rejectedfiles()
        {
            return View();
        }
    }
}

Controllers/Region/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.Region
{
    public class RegionController : Controller
    {
        // GET: Region
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Region()
        {
            return View();
        }

    }
}

Controllers/ZoneCity/ZoneCityController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DengiAdvisor_CRM.Core.UI.Controllers.ZoneCity
{
    public class ZoneCityController : Controller
    {
        // GET: ZoneCity
        public ActionResult Zone()
        {
            return View();
        }
        public ActionResult City()
        {
            return View();
        }
        public ActionResult Region()
        {
            return View();
        }
    }
}

Views/DSA/DSAUser.cshtml
@{
    ViewBag.Title = "DSAUser";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<style type="text/css">
    .userpop a p {
        display: none;
    }

    .userpop a:hover p {
        display: table-row-group;
    }
</style>

<div class="row">
    <!-- subscribe start -->
    <div class="col-md-12">
        <div class="bt-wizard " id="tabswizard">
            <div class="userpop" style="text-align:right">
                <input type="hidden" id="hiddeneditnofification" />
                <a onclick="NewUser();" data-target=".bs-example-modal-sm" role="button" class="pc-link">
                    <i class="fa fa-user-plus" style="font-size: x-large;color: #1f395f"></i>

                </a>&nbsp;<!--data-toggle="modal"-->
                <a onclick="GetUser();" data-target=".bs-example-modal-sm" role="button" class="pc-link">
                    <i class="fa fa-edit" style="font-size: x-large;color: #1f395f"></i>

                </a>
                &nbsp;
                <a data-toggle="modal" data-target=".bs-example-modal-sm" role="button" class="pc-link">
                    <i class="fa fa-trash" style="font-size: x-large;color: #1f395f"></i>
                </a>
            </div>

            <div class="pt-1 bg-primary"></div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header" style="height: 10px;padding: 15px 10px 30px;background-color:#1f395f;">
                            <h5 style="color: white">DSA List</h5>
                        </div>
                        <div class="card-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-5">
                                        <label class="radio-inline">
                                            <input type="radio" id="name" name="searchby" value="Name" class="radioBtnClass">Name
                                        </label>&nbsp;&nbsp;
                                        @*<label class="radio-inline">
                                                <input type="radio" id="role" name="searchby" value="Role" class="radioBtnClass">Role
                                            </label>&nbsp;&nbsp;*@
                                        <label class="radio-inline">
                                            <input type="radio" id="email" name="searchby" value="Email" class="radioBtnClass">Email
                                        </label>&nbsp;&nbsp;
                                        <label class="radio-inline">
                                            <input type="radio" id="contactno" name="searchby" value="ContactNo" class="radioBtnClass">ContactNo
                                        </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <input type="text" id="search" name="search" style="height:30px" class="form-control" />
                                    </div>
                                    <div class="col-lg-3">
                                        <a onclick="SearchUser();" role="button" class="pc-link">
                                            <i class="fa fa-search" style="font-size: x-large;color: #1f395f"></i>
                                        </a>

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12"><br /></div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div style="margin:0 auto" class="tablecontainer table-scrollable">
                                            <div class="table-responsive">
                                                <table id="tbldsalist" class="table display full-width"
                                                       style="border-collapse:collapse; color:black; text-align:justify">
                                                    <thead style="background-color:darkblue; color:white">
                                                        <tr>
                                                            <th></th>
                                                            <th>Name</th>
                                                            <th>Position</th>
                                                            <th>Office</th>
                                                            <th>Salary</th>
                                                        </tr>
                                                    </thead>

                                                    <tbody>
                                                    </tbody>
                                                </table>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
    <!-- subscribe end -->

    <div class="modal" id="myModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">NEW DSA USER REGISTRATION </h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body" style="padding: 0px 0px 0px;">
                    <div class="row">

                        <div class="col-lg-12">
                            <div class="" id="tabswizard">

                                <div class="tab-content card" style="margin-bottom: 30px;">
                                    <div class="pt-1 bg-primary"></div>
                                    <div class="tab-pane card-body pt-4 show active" id="tabs-t-tab1">
                                        <form>
                                            <div class="row text-danger" id="diverror">
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <label>Select DSA Name :</label>
                                                    <select id="ddldsalist" class="form-control">
                                                        <option>Select DSA</option>
                                                    </select>
                                                </div>
                                                <div class="col-lg-4">
                                                    <label>First Name </label>
                                                    <input type="text" class="form-control" name="DSANAME" />
                                                </div>
                                                <div class="col-lg-4" style="margin-top:10px;">
                                                    <label>Last Name</label>
                                                    <input type="text" class="form-control" name="DSANAME" />
                                                </div>
                                                <div class="col-lg-4" style="margin-top:10px;">
                                                    <label>Email </label>
                                                    <input type="text" class="form-control" name="DSANAME" />
                                                </div>

                                                @*<div class="col-lg-4" style="margin-top:10px;">
                                                        <label>Password </label>
                                                        <input type="text" class="form-control" name="DSANAME" />
                                                    </div>*@

                                                <div class="col-lg-4" style="margin-top:10px;">
                                                    <label>Mobile No</label>
                                                    <input type="text" class="form-control" name="DSANAME" />
                                                </div>

                                                <div class="col-lg-4" style="margin-top:10px;">
                                                    <label>Aadhar No</label>
                                                    <input type="text" class="form-control" name="DSANAME" />
                                                </div>


                                                @*<div class="col-lg-12" style="margin-top: 10px;background-color: #f4f4f4;padding:10px;">
                                                        <input type="button" class="btn btn-danger" name="submit" value="Submit" />
                                                    </div>*@
                                                <div class="col-lg-12  text-right" style="padding:0px;">
                                                    <br />
                                                    <input type="button" id="btnsavedsa" class="btn btn-dark" style="background-color: #1f395f" name="btnsavedsa" value="Submit" />
                                                </div>
                                            </div>
                                        </form>
                                    </div>


                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>


</div>

<script src="~/assets/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
    function NewUser() {
        $("#btnsubmit").attr('value', 'Save');
        $('#txtuserfirstname').val('');
        $('#txtuserlastname').val('');
        $('#txtusermobilenumber').val('');
        $('#txtuseremail').val('');
        $('#txtuserpassword').val('');
        $('input:checkbox').prop('checked', '');
        $('#txtuseremail').removeAttr('readonly');
        $('#myModal').modal('show');
        $('#dialogheadertext').text('Add New Office User');
        $('#txtuseremail').removeAttr('readonly');
        $('#txtuserfirstname').removeAttr('readonly');
        $('#txtuserlastname').removeAttr('readonly');
        $('#txtusermobilenumber').removeAttr('readonly');
    };
    function rolelist() {
        $('#ddldsalist').empty()
        $('#ddldsalist').append('<option value="0">' + '--Select---' + '</option>');

        $.ajax({
            type: 'GET',
            url: 'http://crm.dengiadvisors.com/api/dsa/GetAllDSA',
            dataType: 'json',
            contentType: false,
            processData: false,
            beforeSend: function (request) {
                request.setRequestHeader("Authorization", "Bearer " + $('#authHeader').val());
                request.setRequestHeader("ar", "5e3d803410d9620e4882497urtde");
            },
            success: function (data) {
                var rolelist = JSON.stringify(data);
                //alert(rolelist);
                $.each(data, function (index, value) {

                    $('#ddldsalist').append('<option value="' +
                        value.Id + '">' + value.Name + '</option>');
                });
            },
            error: function (response) {
                var messagedata = JSON.parse(response.responseText)
                alert(messagedata.Message);
            }
        });

    }

    $(document).ready(function () {
        rolelist();
    })
</script>

Views/DSA/Rought.cshtml
@{
    ViewBag.Title = "Rought";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">DSA</a></li>
                    <li class="breadcrumb-item">User Registration</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">


    <div class="col-lg-12">
        <div class="bt-wizard" id="tabswizard">
            <ul class="nav nav-pills">
                <li class="nav-item"><a href="#tabs-t-tab1" class="nav-link rounded-0 active" data-toggle="tab">Add New DSA User's</a></li>
                <li class="nav-item"><a href="#tabs-t-tab2" class="nav-link rounded-0" data-toggle="tab">DSA User's List</a></li>
            </ul>
            <div class="tab-content card">
                <div class="pt-1 bg-primary"></div>
                <div class="tab-pane card-body pt-4 show active" id="tabs-t-tab1">
                    <form>
                        <div class="row">
                            <div class="col-lg-4">
                                <label>Select DSA Name :</label>
                                <select class="form-control">
                                    <option>Raman Comapny Limited</option>
                                    <option>Relince</option>
                                    <option>HDFC</option>
                                </select>
                            </div>
                            <div class="col-lg-4">
                                <label>First Name </label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>
                            <div class="col-lg-4" style="margin-top:10px;">
                                <label>Last Name</label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>
                            <div class="col-lg-4" style="margin-top:10px;">
                                <label>Email </label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>

                            <div class="col-lg-4" style="margin-top:10px;">
                                <label>Password </label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>

                            <div class="col-lg-4" style="margin-top:10px;">
                                <label>Mobile No</label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>

                            <div class="col-lg-4" style="margin-top:10px;">
                                <label>Aadhar No</label>
                                <input type="text" class="form-control" name="DSANAME" />
                            </div>


                            <div class="col-lg-12" style="margin-top: 10px;background-color: #f4f4f4;padding:10px;">
                                <input type="button" class="btn btn-danger" name="submit" value="Submit" />
                            </div>

                        </div>
                    </form>
                </div>
                <div class="tab-pane card-body pt-4" id="tabs-t-tab2">
                    <form>
                        <div class="form-group row">
                            <label for="tabs-t-sate" class="col-sm-3 col-form-label">State</label>
                            <div class="col-sm-9">
                                <select class="form-control" id="tabs-t-sate">
                                    <option>Select State</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="tabs-t-address" class="col-sm-3 col-form-label">Address</label>
                            <div class="col-sm-9">
                                <textarea class="form-control" id="tabs-t-address" rows="3" spellcheck="false"></textarea>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>

Views/Office/UserEmailVerification.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="">
    <meta name="Dengi Advertisors" content="Dengi Advertisors" />
    <!-- Favicon icon -->
    <link rel="icon" href="assets/images/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="/assets/css/plugins/dataTables.bootstrap4.min.css">
    <!-- font css -->
    <link rel="stylesheet" href="/assets/fonts/font-awsome-pro/css/pro.min.css">
    <link rel="stylesheet" href="/assets/fonts/feather.css">
    <link rel="stylesheet" href="/assets/fonts/fontawesome.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/customizer.css">
</head>

<body style="margin: 60px auto auto">
    <br><center style="width: 100%; height:100%;">
        <div style="max-width: 600px; " class="card">
            <div class="card-header">
                <img src="~/assets/images/logo.jpg" alt="">
                <div class="text">
                    <hr>
                    <h2>Activate Your Account</h2>
                    <input type="hidden" id="usertype" value="@ViewBag.usertype" />
                </div>
            </div>
            <div class="card-body">
                <div class="text-author">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i data-feather="user"></i></span>
                        </div>
                        <input type="email" id="txtsigninid" style="background-color:white" readonly="readonly"
                               class="form-control"
                               value="@ViewBag.UserEmail" placeholder="EmailId">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i data-feather="key"></i></span>
                        </div>
                        <input type="password" id="txtpassword" onmouseout="validateSignInPassword();" class="form-control" placeholder="Password">
                    </div>

                </div><hr />
                <p><a href="#" class="btn btn-primary" style="background-color: #0D2352;" onclick="activate()">Save</a></p>
            </div>

        </div>

    </center>
</body>

</html>

<script src="~/scripts/config.js"></script>
<script src="~/scripts/crmAjax.js"></script>
<script src="~/scripts/crmcache.js"></script>
<script src="~/scripts/helper.js"></script>

<script>
    function activate()
    {
        var usertype = $("$usertype").val();
        if (usertype == "user")
        {
            var pData = "{\"Email\":\"" + $('#txtsigninid').val() + "\",\"Password\":\"" + $('#txtpassword').val() + "\"}";
            crmAjax.send({
                url: crmNS.api.url,
                api: 'api/security/UserActivation',
                dataType: 'json',
                data: pData,
                fileControl: "",
                success: function (status, data, errors) {
                    var jsondata = JSON.stringify(data, null, " ");
                    var arr = jQuery.parseJSON(jsondata);
                    window.location.href = '@Url.Action("success", "Office")';
                },
                error: function (status, data, errors) {
                    alert("error");
                }
            });
        }
        else
        {
                var pData = "{\"Email\":\"" + $('#txtsigninid').val() + "\",\"Password\":\"" + $('#txtpassword').val() + "\"}";
            crmAjax.send({
                url: crmNS.api.url,
                api: 'api/bank/BankerActivation',
                dataType: 'json',
                data: pData,
                fileControl: "",
                success: function (status, data, errors) {
                    var jsondata = JSON.stringify(data, null, " ");
                    var arr = jQuery.parseJSON(jsondata);
                    window.location.href = '@Url.Action("success", "Office")';
                },
                error: function (status, data, errors) {
                    alert("error");
                }
            });
        }
    }
</script>

<script src="/assets/js/vendor-all.min.js"></script>
<script src="/assets/js/plugins/bootstrap.min.js"></script>
<script src="/assets/js/plugins/feather.min.js"></script>
<script src="/assets/js/pcoded.min.js"></script>
<script src="../../../../cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="/assets/js/plugins/clipboard.min.js"></script>
<script src="/assets/js/uikit.min.js"></script>

<script src="/assets/js/plugins/jquery.dataTables.min.js"></script>
<script src="/assets/js/plugins/dataTables.bootstrap4.min.js"></script>
<!-- Apex Chart -->
<script src="/assets/js/plugins/apexcharts.min.js"></script>
<script src="/assets/js/pages/todo.js"></script>

Views/ZoneCity/City.cshtml
@{
    ViewBag.Title = "City";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<h2>City</h2>

Views/ZoneCity/Zone.cshtml
@{
    ViewBag.Title = "Zone";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<h2>Zone</h2>